# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/imgtk',
                'doc_host': 'https://alexlewzey.github.io',
                'git_url': 'https://github.com/alexlewzey/imgtk',
                'lib_path': 'imgtk'},
  'syms': { 'imgtk.imgtk': { 'imgtk.imgtk.fmter': ('imgtk.html#fmter', 'imgtk/imgtk.py'),
                             'imgtk.imgtk.main': ('imgtk.html#main', 'imgtk/imgtk.py'),
                             'imgtk.imgtk.pixel_color': ('imgtk.html#pixel_color', 'imgtk/imgtk.py'),
                             'imgtk.imgtk.pixel_hex': ('imgtk.html#pixel_hex', 'imgtk/imgtk.py'),
                             'imgtk.imgtk.pixel_rgb': ('imgtk.html#pixel_rgb', 'imgtk/imgtk.py'),
                             'imgtk.imgtk.recolor': ('imgtk.html#recolor', 'imgtk/imgtk.py'),
                             'imgtk.imgtk.rgb2hex': ('imgtk.html#rgb2hex', 'imgtk/imgtk.py')}}}
