# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/imgtk',
                'doc_host': 'https://alexlewzey.github.io',
                'git_url': 'https://github.com/alexlewzey/imgtk',
                'lib_path': 'imgtk'},
  'syms': { 'imgtk.core': { 'imgtk.core.fmter': ('imgtk.html#fmter', 'imgtk/core.py'),
                            'imgtk.core.pixel_color': ('imgtk.html#pixel_color', 'imgtk/core.py'),
                            'imgtk.core.pixel_hex': ('imgtk.html#pixel_hex', 'imgtk/core.py'),
                            'imgtk.core.pixel_rgb': ('imgtk.html#pixel_rgb', 'imgtk/core.py'),
                            'imgtk.core.recolor': ('imgtk.html#recolor', 'imgtk/core.py'),
                            'imgtk.core.rgb2hex': ('imgtk.html#rgb2hex', 'imgtk/core.py')}}}
